name: Deploy to Staging with Smoke Tests

on:
  push:
    branches: [ hotfix/smoke-watchdog-squeeze-monitor ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Run Smoke Tests
      env:
        API_BASE_URL: https://amc-trader.onrender.com
      run: |
        python ops/smoke/squeeze_smoke.py
    
    - name: Upload smoke test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: smoke-test-results
        path: ops/smoke/
    
    - name: Comment PR with results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '✅ Smoke tests completed. Check artifacts for detailed results.'
          })

  deploy-staging:
    runs-on: ubuntu-latest
    needs: smoke-test
    if: github.ref == 'refs/heads/hotfix/smoke-watchdog-squeeze-monitor'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Staging
      run: |
        echo "🚀 Staging deployment would happen here"
        echo "Environment: staging"
        echo "Branch: ${{ github.ref }}"
    
    - name: Wait for deployment
      run: sleep 30
    
    - name: Post-deployment smoke test
      env:
        API_BASE_URL: https://amc-trader.onrender.com  # Would be staging URL
      run: |
        python ops/smoke/squeeze_smoke.py